//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.SERVICIO.WS.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajeExcepcion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeExcepcion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPC.SISDUC.SERVICIO.WS.Recursos.MensajeExcepcion", typeof(MensajeExcepcion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe o no esta implementado los metodos para entidad que desea.
        /// </summary>
        internal static string ComboEntidadNoImplement {
            get {
                return ResourceManager.GetString("ComboEntidadNoImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado actual debe ser Cerrada.
        /// </summary>
        internal static string EstadoCerrada {
            get {
                return ResourceManager.GetString("EstadoCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado actual puede ser EnProceso.
        /// </summary>
        internal static string EstadoEnProceso {
            get {
                return ResourceManager.GetString("EstadoEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error: {0} - {1}.
        /// </summary>
        internal static string OcurrioError {
            get {
                return ResourceManager.GetString("OcurrioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema al utilizar el servicio: {0} - {1}.
        /// </summary>
        internal static string OcurrioProblemaServicio {
            get {
                return ResourceManager.GetString("OcurrioProblemaServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Flujo de Verificacion debe tener un valor.
        /// </summary>
        internal static string TextoFlujoVerificacion {
            get {
                return ResourceManager.GetString("TextoFlujoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Motivo no tiene valor.
        /// </summary>
        internal static string TextoMotivo {
            get {
                return ResourceManager.GetString("TextoMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Resultado no tiene valor.
        /// </summary>
        internal static string TextoResultado {
            get {
                return ResourceManager.GetString("TextoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo de Verificacion debe tener un valor.
        /// </summary>
        internal static string TextoTipoVerificacion {
            get {
                return ResourceManager.GetString("TextoTipoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verificacion.Estado.
        /// </summary>
        internal static string UbicacionEstadoVerificacion {
            get {
                return ResourceManager.GetString("UbicacionEstadoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verificacion.FlujoVerificacion.
        /// </summary>
        internal static string UbicacionFlujoVerificacion {
            get {
                return ResourceManager.GetString("UbicacionFlujoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verifiacion.Motivo.
        /// </summary>
        internal static string UbicacionMotivo {
            get {
                return ResourceManager.GetString("UbicacionMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verificacion.Resultado.
        /// </summary>
        internal static string UbicacionResultadoVerificacion {
            get {
                return ResourceManager.GetString("UbicacionResultadoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verificacion.TipoVerificacion.
        /// </summary>
        internal static string UbicacionTipoVerificacion {
            get {
                return ResourceManager.GetString("UbicacionTipoVerificacion", resourceCulture);
            }
        }
    }
}
