//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.WEB.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constantes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPC.SISDUC.WEB.Recursos.Constantes", typeof(Constantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sAMAccountName.
        /// </summary>
        internal static string AD_account {
            get {
                return ResourceManager.GetString("AD_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sn.
        /// </summary>
        internal static string AD_apellidos {
            get {
                return ResourceManager.GetString("AD_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a company.
        /// </summary>
        internal static string AD_compania {
            get {
                return ResourceManager.GetString("AD_compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a department.
        /// </summary>
        internal static string AD_departamento {
            get {
                return ResourceManager.GetString("AD_departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mail.
        /// </summary>
        internal static string AD_Email {
            get {
                return ResourceManager.GetString("AD_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a memberOf.
        /// </summary>
        internal static string AD_grupos {
            get {
                return ResourceManager.GetString("AD_grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a givenName.
        /// </summary>
        internal static string AD_nombrecompleto {
            get {
                return ResourceManager.GetString("AD_nombrecompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        internal static string AD_nombres {
            get {
                return ResourceManager.GetString("AD_nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a title.
        /// </summary>
        internal static string AD_titulo {
            get {
                return ResourceManager.GetString("AD_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró registros para la búsqueda.
        /// </summary>
        internal static string BusquedaVacia {
            get {
                return ResourceManager.GetString("BusquedaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 57.
        /// </summary>
        internal static string CanalSVD {
            get {
                return ResourceManager.GetString("CanalSVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Caso Default.
        /// </summary>
        internal static string CaseDefault {
            get {
                return ResourceManager.GetString("CaseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conforme.
        /// </summary>
        internal static string Conforme {
            get {
                return ResourceManager.GetString("Conforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Int. .
        /// </summary>
        internal static string IntAbreviado {
            get {
                return ResourceManager.GetString("IntAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Conforme.
        /// </summary>
        internal static string NoConforme {
            get {
                return ResourceManager.GetString("NoConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. .
        /// </summary>
        internal static string NroAbreviado {
            get {
                return ResourceManager.GetString("NroAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        internal static string Pendiente {
            get {
                return ResourceManager.GetString("Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud.
        /// </summary>
        internal static string PestaniaSolicitud {
            get {
                return ResourceManager.GetString("PestaniaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Historial.
        /// </summary>
        internal static string PestaniaSolicitudH {
            get {
                return ResourceManager.GetString("PestaniaSolicitudH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación.
        /// </summary>
        internal static string PestaniaVerificacion {
            get {
                return ResourceManager.GetString("PestaniaVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación Historial.
        /// </summary>
        internal static string PestaniaVerificacionH {
            get {
                return ResourceManager.GetString("PestaniaVerificacionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardo el registro satisfactoriamente.
        /// </summary>
        internal static string RegistroSatisfactorio {
            get {
                return ResourceManager.GetString("RegistroSatisfactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- SELECCIONE --.
        /// </summary>
        internal static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -1.
        /// </summary>
        internal static string SeleccioneValor {
            get {
                return ResourceManager.GetString("SeleccioneValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string TextoCero {
            get {
                return ResourceManager.GetString("TextoCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  .
        /// </summary>
        internal static string TextoEspacio {
            get {
                return ResourceManager.GetString("TextoEspacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a false.
        /// </summary>
        internal static string textoFalse {
            get {
                return ResourceManager.GetString("textoFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string TextoNo {
            get {
                return ResourceManager.GetString("TextoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string TextoSi {
            get {
                return ResourceManager.GetString("TextoSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a true.
        /// </summary>
        internal static string textoTrue {
            get {
                return ResourceManager.GetString("textoTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string TextoVacio {
            get {
                return ResourceManager.GetString("TextoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones de Menú.
        /// </summary>
        internal static string TituloMensajeOpcionesMenu {
            get {
                return ResourceManager.GetString("TituloMensajeOpcionesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- TODOS --.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string TodosValor {
            get {
                return ResourceManager.GetString("TodosValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urb. .
        /// </summary>
        internal static string UrbAbreviado {
            get {
                return ResourceManager.GetString("UrbAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a javascript:NavigateURLnull().
        /// </summary>
        internal static string URLNull {
            get {
                return ResourceManager.GetString("URLNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MotorSVD.
        /// </summary>
        internal static string UsuarioMotor {
            get {
                return ResourceManager.GetString("UsuarioMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ValorCero {
            get {
                return ResourceManager.GetString("ValorCero", resourceCulture);
            }
        }
    }
}
